import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@/components/Navigation/Navigation";

export const metadata: Metadata = {
  title: "Hazem Ben Abdelhafidh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` font-mono  antialiased  flex  justify-center p-6`}>
        <div className=" max-w-4xl w-[56rem]">
          <Navigation />
          {children}
        </div>
      </body>
    </html>
  );
}
